services:
  postgres:
    image: postgres:16
    container_name: team-postgres

    environment:
      POSTGRES_DB: teamdb
      POSTGRES_USER: teamuser
      POSTGRES_PASSWORD: teampassword

    ports:
      - "8100:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
