services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.14.130.171:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  
