# ============================================================
# Docker Compose Configuration
# ============================================================
spring.boot.docker.compose.enabled=false

# PostgreSQL runtime configuration.
# Override these with environment variables when needed.

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:8100/team10leap}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:n3u3d4!}}
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================================
# Alpaca configuration
# ============================================================

alpaca.api-key=${ALPACA_API_KEY:PK54SSI76QWZTBYFF376G7QTQO}
alpaca.api-secret=${ALPACA_API_SECRET:6RVcEtGCM8cWKPVxXTTvqthWLU5ktfGjVVZeC25ZCGQP}


# ============================================================
# Alpaca data endpoints
# ============================================================

alpaca.stocks-base-url=https://data.alpaca.markets/v2/stocks

alpaca.crypto-base-url=https://data.alpaca.markets/v1beta3/crypto/us

alpaca.forex-base-url=https://data.alpaca.markets/v1beta1/forex

# ============================================================
# Docker compose configuration
# ============================================================
spring.docker.compose.enabled=false

# ============================================================
# Refresh configuration
# ============================================================

alpaca.refresh-all=true

alpaca.refresh-stocks=true

alpaca.refresh-crypto=true

alpaca.refresh-forex=false

alpaca.refresh-delay-ms=5000

alpaca.max-retries=2

alpaca.retry-backoff-ms=2500

alpaca.request-timeout-ms=5000

alpaca.skip-outside-market-hours=true

# ============================================================
# MyBatis configuration
# ============================================================

mybatis.configuration.map-underscore-to-camel-case=true

# ============================================================
# Kafka configuration
# ============================================================

# Kafka port
spring.kafka.bootstrap.servers=localhost:9092
app.kafka.topics.order-pending=order-pending-topic

# Producer stuff
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerial>
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.Jso>

# Consumer stuff
spring.kafka.consumer.group-id=trading-execution-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDese>
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.J>
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.entities.Or>
