DROP TABLE IF EXISTS holdings;
DROP TABLE IF EXISTS clients;

CREATE TABLE clients (
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    cash_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE holdings (
    hold_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    ticker VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    updated_at DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT fk_client
        FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
        ON DELETE CASCADE,

    CONSTRAINT unique_client_ticker
        UNIQUE (client_id, ticker)
);
